// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzS6HOKntkVx56b1YtKpk6pqmov5BoAIE',
    appId: '1:113054719642:ios:ea9a63edd838c751470923',
    messagingSenderId: '113054719642',
    projectId: 'construction-managerr',
    storageBucket: 'construction-managerr.firebasestorage.app',
    iosBundleId: 'com.example.constructionManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzS6HOKntkVx56b1YtKpk6pqmov5BoAIE',
    appId: '1:113054719642:ios:ea9a63edd838c751470923',
    messagingSenderId: '113054719642',
    projectId: 'construction-managerr',
    storageBucket: 'construction-managerr.firebasestorage.app',
    iosBundleId: 'com.example.constructionManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVtG5i7vpMabC6Uu8_t3vFWYSHESpAB8k',
    appId: '1:113054719642:web:4e45e8dfffdde45c470923',
    messagingSenderId: '113054719642',
    projectId: 'construction-managerr',
    authDomain: 'construction-managerr.firebaseapp.com',
    storageBucket: 'construction-managerr.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVtG5i7vpMabC6Uu8_t3vFWYSHESpAB8k',
    appId: '1:113054719642:web:4e45e8dfffdde45c470923',
    messagingSenderId: '113054719642',
    projectId: 'construction-managerr',
    authDomain: 'construction-managerr.firebaseapp.com',
    storageBucket: 'construction-managerr.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHu7_IzAz3xB-tlBjSKPltL0SWxm--cR4',
    appId: '1:113054719642:android:7f0ca5ed83a2d702470923',
    messagingSenderId: '113054719642',
    projectId: 'construction-managerr',
    storageBucket: 'construction-managerr.firebasestorage.app',
  );

}